// tslint:disable

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/batchUpdate": {
    /** Batch update of placement, booking and campaign data */
    post: operations["batchUpdate"];
  };
  "/api/v1/batchDelete": {
    /** Batch delete of placements, booking or campaign */
    post: operations["batchDelete"];
  };
}

export interface components {
  schemas: {
    /** Empty Struct (Used mostly for Void RPC responses) */
    Unit: { [key: string]: unknown };
    /** Request batch update/create of placements, campaigns and bookings */
    BatchUpdateReq: {
      reqId?: string;
      placements?: components["schemas"]["ApiPlacement"][];
      campaigns?: components["schemas"]["ApiCampaign"][];
      bookings?: components["schemas"]["ApiBooking"][];
    };
    /** An advertisement placement */
    ApiPlacement: {
      identifier: components["schemas"]["ApiPlacementId"];
      name: components["schemas"]["strings_StringNE"];
      description: components["schemas"]["common_Notes"];
      summary?: string;
      searchContent?: string;
      category: components["schemas"]["db_PlacementCategory"];
      originalSpecs?: components["schemas"]["common_UrlResource"][];
      images?: components["schemas"]["common_UrlResource"][];
      documents?: components["schemas"]["common_UrlResource"][];
      location?: components["schemas"]["db_PlacementLocation"] | null;
      specifications: components["schemas"]["artworkspec_Specifications"];
      isDraft?: boolean;
      isVerified?: boolean;
      isDeprecated?: boolean;
      deprecatedAt?: components["schemas"]["Instant"] | null;
      activeStart?: components["schemas"]["LocalDate"] | null;
      activeEnd?: components["schemas"]["LocalDate"] | null;
      publicSearchable?: boolean;
      attributes?: components["schemas"]["artworkspec_Attributes"];
      version?: components["schemas"]["db_Version"];
      lastVerified?: components["schemas"]["Instant"] | null;
    };
    ApiPlacementId: string;
    strings_StringNE: string;
    common_Notes: components["schemas"]["strings_StringMD"];
    strings_StringMD: string;
    db_PlacementCategory:
      | "AUDIO"
      | "BROADCAST"
      | "CINEMA"
      | "DISPLAY"
      | "NATIVE"
      | "ONLINE"
      | "DOOH"
      | "PRINT_OOH"
      | "OOH_TRANSIT"
      | "PRINT_MAGAZINE"
      | "PRINT_NEWSPAPER"
      | "RICHMEDIA"
      | "SEM"
      | "SOCIAL"
      | "VIDEO"
      | "OTHER";
    /** A Url/Datasource with name and notes */
    common_UrlResource: {
      name?: components["schemas"]["strings_StringNE"] | null;
      data: components["schemas"]["common_DataOrigin"];
      notes?: components["schemas"]["common_Notes"] | null;
      fileSize?: number | null;
    };
    /** Choice of Data Source (URL only) */
    common_DataOrigin: {
      url: components["schemas"]["common_Url"];
    };
    common_Url: string;
    db_PlacementLocation: {
      siteNumber?: string | null;
      direction?: string | null;
      address?: components["schemas"]["strings_StringML"] | null;
      suburb?: string | null;
      postcode?: string | null;
      state?: string | null;
      country?: string | null;
    };
    strings_StringML: string;
    /** Placement Specifications */
    artworkspec_Specifications: {
      components: components["schemas"]["artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_ArtworkSpec"][];
    };
    /** Artwork Specification - one of a family of appropriate properties per media type */
    artworkspec_ArtworkSpec:
      | {
          digitalStatic: components["schemas"]["artworkspec_DigitalStaticMedia"];
        }
      | {
          animated: components["schemas"]["artworkspec_AnimatedMedia"];
        }
      | {
          html5: components["schemas"]["artworkspec_Html5Media"];
        }
      | {
          video: components["schemas"]["artworkspec_Video"];
        }
      | {
          audio: components["schemas"]["artworkspec_Audio"];
        }
      | {
          copy: components["schemas"]["artworkspec_CopyMedia"];
        }
      | {
          newspaper: components["schemas"]["artworkspec_PrintNewspaper"];
        }
      | {
          magazine: components["schemas"]["artworkspec_PrintMagazine"];
        }
      | {
          printOOH: components["schemas"]["artworkspec_PrintOOH"];
        };
    artworkspec_DigitalStaticMedia: {
      dimensions: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalMediaDimensions"];
      maxFileSize?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmount"]
        | null;
      safeZone?:
        | components["schemas"]["artworkspec_Annotated_common_Unit"]
        | null;
      resolution?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalResolution"]
        | null;
      aspectRatios?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoAspectRatios"]
        | null;
      color?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalColorSpace"]
        | null;
      border?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Border"]
        | null;
      formats: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_StaticMediaFormat"];
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    artworkspec_DigitalMediaDimensions: components["schemas"]["artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_DigitalMediaDimension"];
    /** Dimension property for Display media - Where combinations of retina/standard and expanded/collapsed are needed. */
    artworkspec_DigitalMediaDimension: {
      pixelDimension: components["schemas"]["artworkspec_PixelDimension"];
      resolutionType?:
        | components["schemas"]["artworkspec_DimensionResolutionType"]
        | null;
      sizeCase?: components["schemas"]["artworkspec_DimensionSizeCase"] | null;
    };
    artworkspec_PixelDimension: {
      width: number;
      height: number;
    };
    /** Dimension Resolution Type (standard or retina) */
    artworkspec_DimensionResolutionType:
      | ("standard" | "retina")
      | {
          other: string;
        };
    /** Dimension size use-case (regular vs expanded or collapsed) */
    artworkspec_DimensionSizeCase:
      | ("regular" | "expanded" | "collapsed")
      | {
          other: string;
        };
    artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_DigitalMediaDimension: components["schemas"]["artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_DigitalMediaDimension"][];
    /** A value with an optional name and metadata */
    artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_DigitalMediaDimension: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      name?: string | null;
      value: components["schemas"]["artworkspec_DigitalMediaDimension"];
    };
    artworkspec_Metadata: {
      notes?: components["schemas"]["common_Notes"] | null;
      images?: components["schemas"]["common_UrlResource"][];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalMediaDimensions: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_DigitalMediaDimensions"];
    };
    /** Amount of data / file size */
    artworkspec_DataAmount: {
      amount: number;
      unit: components["schemas"]["artworkspec_FileSizeUnit"];
    };
    artworkspec_FileSizeUnit: "kb" | "mb" | "gb";
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmount: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_DataAmount"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_common_Unit: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["Unit"];
    };
    artworkspec_DigitalResolution: {
      amount: number;
      unit: components["schemas"]["artworkspec_DigitalResolutionUnit"];
    };
    /** Digital Resolution */
    artworkspec_DigitalResolutionUnit:
      | ("DPI" | "PPI")
      | {
          other: string;
        };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalResolution: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_DigitalResolution"];
    };
    artworkspec_VideoAspectRatios: {
      square?: components["schemas"]["Unit"] | null;
      portrait_9_16?: components["schemas"]["Unit"] | null;
      landscape_16_9?: components["schemas"]["Unit"] | null;
      portrait_4_5?: components["schemas"]["Unit"] | null;
      custom?: components["schemas"]["artworkspec_VectorAnnotated_kachemedia_specsheet_artworkspec_CustomAspectRatio"];
      other?: components["schemas"]["artworkspec_VectorAnnotated_String"];
    };
    artworkspec_CustomAspectRatio: {
      name: string;
      width: number;
      height: number;
    };
    artworkspec_VectorAnnotated_kachemedia_specsheet_artworkspec_CustomAspectRatio: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_CustomAspectRatio"][];
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_CustomAspectRatio: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_CustomAspectRatio"];
    };
    artworkspec_VectorAnnotated_String: components["schemas"]["artworkspec_Annotated_String"][];
    /** A value - optionally with metadata */
    artworkspec_Annotated_String: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: string;
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoAspectRatios: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_VideoAspectRatios"];
    };
    /** Color spaces */
    artworkspec_DigitalColorSpace: {
      RGB?: components["schemas"]["Unit"] | null;
      HEX?: components["schemas"]["Unit"] | null;
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalColorSpace: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_DigitalColorSpace"];
    };
    artworkspec_Border:
      | "singlePixel"
      | {
          other: string;
        };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_Border: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_Border"];
    };
    /** Static media format */
    artworkspec_StaticMediaFormat: {
      jpg?: components["schemas"]["artworkspec_JPG"] | null;
      bmp?: components["schemas"]["artworkspec_BMP"] | null;
      gif?: components["schemas"]["artworkspec_GIF"] | null;
      png?: components["schemas"]["artworkspec_PNG"] | null;
      eps?: components["schemas"]["artworkspec_EPS"] | null;
      ai?: components["schemas"]["artworkspec_AI"] | null;
      tiff?: components["schemas"]["artworkspec_TIFF"] | null;
      psdLayered?: components["schemas"]["artworkspec_PSD"] | null;
      psdFlattened?: components["schemas"]["artworkspec_PSD"] | null;
      svg?: components["schemas"]["artworkspec_SVG"] | null;
      other?: components["schemas"]["artworkspec_VectorAnnotated_String"];
    };
    /** JPG Specification details */
    artworkspec_JPG: { [key: string]: unknown };
    /** BMP Specification details */
    artworkspec_BMP: { [key: string]: unknown };
    /** GIF Specification details */
    artworkspec_GIF: {
      transparency?: components["schemas"]["Unit"] | null;
    };
    /** PNG Specification details */
    artworkspec_PNG: {
      transparency?: components["schemas"]["Unit"] | null;
      png8?: components["schemas"]["artworkspec_PNGFormat"] | null;
      png24?: components["schemas"]["artworkspec_PNGFormat"] | null;
    };
    artworkspec_PNGFormat: { [key: string]: unknown };
    /** EPS Specification details */
    artworkspec_EPS: {
      convertToOutline?: components["schemas"]["Unit"] | null;
    };
    artworkspec_AI: {
      convertToOutline?: components["schemas"]["Unit"] | null;
    };
    /** TIFF Specification details */
    artworkspec_TIFF: { [key: string]: unknown };
    artworkspec_PSD: {
      psdExampleUrl?: components["schemas"]["common_Url"] | null;
    };
    /** SVG Specification details */
    artworkspec_SVG: { [key: string]: unknown };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_StaticMediaFormat: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_StaticMediaFormat"];
    };
    artworkspec_Attributes: components["schemas"]["artworkspec_KeyValueAttribute"][];
    artworkspec_KeyValueAttribute: {
      name: string;
      value: components["schemas"]["common_Notes"];
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
    };
    /** Animated Media */
    artworkspec_AnimatedMedia: {
      dimensions: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalMediaDimensions"];
      durations: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Durations"];
      loop?: components["schemas"]["artworkspec_Annotated_common_Unit"] | null;
      loopCount?: components["schemas"]["artworkspec_Annotated_Word16"] | null;
      endWithStaticFrame: components["schemas"]["artworkspec_Annotated_Bool"];
      safeZone?:
        | components["schemas"]["artworkspec_Annotated_common_Unit"]
        | null;
      resolution?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalResolution"]
        | null;
      color?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_RGBOnlyColorSpace"]
        | null;
      border?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Border"]
        | null;
      formats: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_AnimatedMediaFormat"];
      maxFileSize?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmount"]
        | null;
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    artworkspec_Durations: components["schemas"]["artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_Duration"];
    artworkspec_Duration: {
      hours?: number | null;
      minutes?: number | null;
      seconds?: number | null;
      milliSeconds?: number | null;
    };
    artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_Duration: components["schemas"]["artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_Duration"][];
    /** A value with an optional name and metadata */
    artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_Duration: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      name?: string | null;
      value: components["schemas"]["artworkspec_Duration"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_Durations: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_Durations"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_Word16: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: number;
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_Bool: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: boolean;
    };
    /** Color spaces */
    artworkspec_RGBOnlyColorSpace: {
      RGB?: components["schemas"]["Unit"] | null;
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_RGBOnlyColorSpace: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_RGBOnlyColorSpace"];
    };
    /** Animated media format */
    artworkspec_AnimatedMediaFormat: {
      gif?: components["schemas"]["artworkspec_GIF"] | null;
      other?: components["schemas"]["artworkspec_VectorAnnotated_String"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_AnimatedMediaFormat: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_AnimatedMediaFormat"];
    };
    /** HTML Media Specification details */
    artworkspec_Html5Media: {
      dimensions: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalMediaDimensions"];
      safeZone?:
        | components["schemas"]["artworkspec_Annotated_common_Unit"]
        | null;
      resolution?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalResolution"]
        | null;
      color?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalColorSpace"]
        | null;
      border?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Border"]
        | null;
      dataAmounts?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmounts"]
        | null;
      formats: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Html5Formats"];
      durations?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Durations"]
        | null;
      frameRate?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_FrameRate"]
        | null;
      loop?: components["schemas"]["artworkspec_Annotated_common_Unit"] | null;
      loopCount?: components["schemas"]["artworkspec_Annotated_Word16"] | null;
      accepted3rdPartyVendors?:
        | components["schemas"]["artworkspec_Attributes"]
        | null;
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    artworkspec_DataAmounts: components["schemas"]["artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_DataAmountProperty"];
    artworkspec_DataAmountProperty: {
      amount: components["schemas"]["artworkspec_DataAmount"];
      kind: components["schemas"]["artworkspec_DataAmountType"];
    };
    artworkspec_DataAmountType:
      | (
          | "total"
          | "initial"
          | "polite"
          | "userInitiated"
          | "adVerificationScripts"
          | "hostedSharedLibrary"
        )
      | {
          other: string;
        };
    artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_DataAmountProperty: components["schemas"]["artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_DataAmountProperty"][];
    /** A value with an optional name and metadata */
    artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_DataAmountProperty: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      name?: string | null;
      value: components["schemas"]["artworkspec_DataAmountProperty"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmounts: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_DataAmounts"];
    };
    /** Html5 formats */
    artworkspec_Html5Formats: {
      static: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_StaticMediaFormat"];
      animated: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_AnimatedMediaFormat"];
      web: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_WebMediaFormat"];
      video?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Html5Video"]
        | null;
    };
    artworkspec_WebMediaFormat: {
      HTML5?: components["schemas"]["Unit"] | null;
      CSS?: components["schemas"]["Unit"] | null;
      JS?: components["schemas"]["Unit"] | null;
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_WebMediaFormat: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_WebMediaFormat"];
    };
    artworkspec_Html5Video: {
      video: components["schemas"]["artworkspec_Video"];
    };
    artworkspec_Video: {
      dimensions: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DigitalMediaDimensions"];
      orientation?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_MediaOrientation"]
        | null;
      aspectRatios?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoAspectRatios"]
        | null;
      safeZone?:
        | components["schemas"]["artworkspec_Annotated_common_Unit"]
        | null;
      durations?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Durations"]
        | null;
      formats: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoFormat"];
      codec?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoCodec"]
        | null;
      frameRate?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_FrameRate"]
        | null;
      profile?: components["schemas"]["artworkspec_Annotated_String"] | null;
      profileLevel?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      bitrate?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_BitRate"]
        | null;
      fieldRender?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      loop?: components["schemas"]["artworkspec_Annotated_common_Unit"] | null;
      loopCount?: components["schemas"]["artworkspec_Annotated_Word16"] | null;
      audio?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoAudioSupport"]
        | null;
      subtitles?:
        | components["schemas"]["artworkspec_Annotated_common_Unit"]
        | null;
      script?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoScriptSupport"]
        | null;
      dataAmounts?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmounts"]
        | null;
      accepted3rdPartyVendors?:
        | components["schemas"]["artworkspec_Attributes"]
        | null;
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    /** Media Orientation */
    artworkspec_MediaOrientation: {
      landscape?: components["schemas"]["Unit"] | null;
      portrait?: components["schemas"]["Unit"] | null;
      square?: components["schemas"]["Unit"] | null;
      other?: components["schemas"]["artworkspec_VectorAnnotated_String"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_MediaOrientation: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_MediaOrientation"];
    };
    /** Video format */
    artworkspec_VideoFormat: {
      MP4?: components["schemas"]["Unit"] | null;
      WebM?: components["schemas"]["Unit"] | null;
      MOV?: components["schemas"]["Unit"] | null;
      WMV?: components["schemas"]["Unit"] | null;
      AVI?: components["schemas"]["Unit"] | null;
      OGG?: components["schemas"]["Unit"] | null;
      ThreeGP?: components["schemas"]["Unit"] | null;
      FLV?: components["schemas"]["Unit"] | null;
      other?: components["schemas"]["artworkspec_VectorAnnotated_String"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoFormat: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_VideoFormat"];
    };
    /** Video codec */
    artworkspec_VideoCodec: {
      avc_h264?: components["schemas"]["Unit"] | null;
      hevc_h265?: components["schemas"]["Unit"] | null;
      mpeg2?: components["schemas"]["Unit"] | null;
      mpeg4?: components["schemas"]["Unit"] | null;
      divx?: components["schemas"]["Unit"] | null;
      Webm_vp9?: components["schemas"]["Unit"] | null;
      Webm_vp8?: components["schemas"]["Unit"] | null;
      ProRes422?: components["schemas"]["Unit"] | null;
      QuickTime?: components["schemas"]["Unit"] | null;
      other?: components["schemas"]["artworkspec_VectorAnnotated_String"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoCodec: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_VideoCodec"];
    };
    artworkspec_FrameRate: {
      value: number;
      unit: components["schemas"]["artworkspec_FrameRateUnit"];
    };
    artworkspec_FrameRateUnit: "perSecond";
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_FrameRate: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_FrameRate"];
    };
    artworkspec_BitRate: {
      value: number;
      unit: components["schemas"]["artworkspec_BitRateUnit"];
    };
    artworkspec_BitRateUnit: "Mbps" | "Kbps";
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_BitRate: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_BitRate"];
    };
    artworkspec_VideoAudioSupport: {
      formats: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_AudioFormat"];
      decibels?: components["schemas"]["artworkspec_Annotated_String"] | null;
      audioBitrate?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_BitRate"]
        | null;
      sampleRate?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_SampleRate"]
        | null;
    };
    /** Audio format */
    artworkspec_AudioFormat: {
      WAV?: components["schemas"]["Unit"] | null;
      AIFF?: components["schemas"]["Unit"] | null;
      MP3?: components["schemas"]["Unit"] | null;
      AAC?: components["schemas"]["Unit"] | null;
      other?: components["schemas"]["artworkspec_VectorAnnotated_String"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_AudioFormat: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_AudioFormat"];
    };
    artworkspec_SampleRate: {
      value: number;
      unit: components["schemas"]["artworkspec_SampleRateUnit"];
    };
    artworkspec_SampleRateUnit: "kiloHertz";
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_SampleRate: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_SampleRate"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoAudioSupport: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_VideoAudioSupport"];
    };
    artworkspec_VideoScriptSupport: {
      scriptFormat: components["schemas"]["artworkspec_VideoScriptFormat"];
    };
    /**
     * See also VideoAspectRatios
     * Video Script format
     */
    artworkspec_VideoScriptFormat: {
      VAST?: components["schemas"]["Unit"] | null;
      VPAID?: components["schemas"]["Unit"] | null;
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_VideoScriptSupport: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_VideoScriptSupport"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_Html5Video: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_Html5Video"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_Html5Formats: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_Html5Formats"];
    };
    /** Audio */
    artworkspec_Audio: {
      durations: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Durations"];
      formats: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_AudioFormat"];
      codecs?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_AudioCodecs"]
        | null;
      bitrate?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_BitRate"]
        | null;
      sampleRate?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_SampleRate"]
        | null;
      decibels?: components["schemas"]["artworkspec_Annotated_String"] | null;
      maxFileSize?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmount"]
        | null;
      adServing?: components["schemas"]["artworkspec_Annotated_String"] | null;
      tracking?: components["schemas"]["artworkspec_Annotated_String"] | null;
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    artworkspec_AudioCodecs: components["schemas"]["artworkspec_VectorNamedAnnotated_String"];
    artworkspec_VectorNamedAnnotated_String: components["schemas"]["artworkspec_NamedAnnotated_String"][];
    /** A value with an optional name and metadata */
    artworkspec_NamedAnnotated_String: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      name?: string | null;
      value: string;
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_AudioCodecs: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_AudioCodecs"];
    };
    artworkspec_CopyMedia: {
      text: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_CopyMediaTextSpecs"];
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    artworkspec_CopyMediaTextSpecs: components["schemas"]["artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_CopyMediaTextSpec"];
    artworkspec_CopyMediaTextSpec: {
      minCharacters?: number | null;
      maxCharacters?: number | null;
      maxFileSize?: components["schemas"]["artworkspec_DataAmount"] | null;
    };
    artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_CopyMediaTextSpec: components["schemas"]["artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_CopyMediaTextSpec"][];
    /** A value with an optional name and metadata */
    artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_CopyMediaTextSpec: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      name?: string | null;
      value: components["schemas"]["artworkspec_CopyMediaTextSpec"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_CopyMediaTextSpecs: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_CopyMediaTextSpecs"];
    };
    artworkspec_PrintNewspaper: {
      dimension: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions"];
      trim?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions"]
        | null;
      additionalPrintDimensions?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_AdditionalPrintDimensions"]
        | null;
      textSafeArea?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintBorderDimensions"]
        | null;
      textFreeGutter?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      bleed?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintBorderDimensions"]
        | null;
      finishedTrimBleed?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions"]
        | null;
      resolution?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintResolution"]
        | null;
      colourProfile?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      separationProfile?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      inkWeightCoverage?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      blackInkLimit?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      dotGain?: components["schemas"]["artworkspec_Annotated_String"] | null;
      highlightSet?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      formats: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintMediaFormat"];
      maxFileSize?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmount"]
        | null;
      font?: components["schemas"]["artworkspec_Annotated_String"] | null;
      spread?: components["schemas"]["artworkspec_Annotated_String"] | null;
      placementInNewspaper?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    artworkspec_PrintDimensions: {
      height: components["schemas"]["artworkspec_PrintDimension"];
      width: components["schemas"]["artworkspec_PrintDimension"];
    };
    artworkspec_PrintDimension: {
      value: number;
      unit: components["schemas"]["artworkspec_DimensionUnit"];
    };
    artworkspec_DimensionUnit: "m" | "cm" | "mm";
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_PrintDimensions"];
    };
    artworkspec_AdditionalPrintDimensions: components["schemas"]["artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_PrintDimensions"];
    artworkspec_VectorNamedAnnotated_kachemedia_specsheet_artworkspec_PrintDimensions: components["schemas"]["artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_PrintDimensions"][];
    /** A value with an optional name and metadata */
    artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_PrintDimensions: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      name?: string | null;
      value: components["schemas"]["artworkspec_PrintDimensions"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_AdditionalPrintDimensions: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_AdditionalPrintDimensions"];
    };
    artworkspec_PrintBorderDimensions: {
      top: components["schemas"]["artworkspec_PrintDimension"];
      left: components["schemas"]["artworkspec_PrintDimension"];
      right: components["schemas"]["artworkspec_PrintDimension"];
      bottom: components["schemas"]["artworkspec_PrintDimension"];
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintBorderDimensions: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_PrintBorderDimensions"];
    };
    artworkspec_PrintResolution: {
      amount: number;
      unit: components["schemas"]["artworkspec_PrintResolutionUnit"];
    };
    /** Print Resolution */
    artworkspec_PrintResolutionUnit:
      | ("DPI" | "LPI")
      | {
          other: string;
        };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintResolution: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_PrintResolution"];
    };
    artworkspec_PrintMediaFormat: {
      pdf?: components["schemas"]["artworkspec_PDF"] | null;
      eps?: components["schemas"]["artworkspec_EPS"] | null;
      ai?: components["schemas"]["artworkspec_AI"] | null;
      indd?: components["schemas"]["artworkspec_INDD"] | null;
      psd?: components["schemas"]["artworkspec_PSD"] | null;
      quarkXPress?: components["schemas"]["artworkspec_QuarkXPress"] | null;
      other?: components["schemas"]["artworkspec_VectorAnnotated_String"];
    };
    /** PDF Specification details */
    artworkspec_PDF: { [key: string]: unknown };
    /** INDD Specification details */
    artworkspec_INDD: { [key: string]: unknown };
    /** QuarkXPress Specification details */
    artworkspec_QuarkXPress: { [key: string]: unknown };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintMediaFormat: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_PrintMediaFormat"];
    };
    artworkspec_PrintMagazine: {
      trim:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions"]
        | null;
      design:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions"]
        | null;
      textSafeArea?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintBorderDimensions"]
        | null;
      bleed?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintBorderDimensions"]
        | null;
      finishedTrimBleed?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions"]
        | null;
      textFreeGutter?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      resolution?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintResolution"]
        | null;
      colourProfile?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      separationProfile?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      inkWeightCoverage?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      formats: components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintMediaFormat"];
      font?: components["schemas"]["artworkspec_Annotated_String"] | null;
      scaling?: components["schemas"]["artworkspec_Annotated_Word16"] | null;
      paperType?: components["schemas"]["artworkspec_Annotated_String"] | null;
      finish?: components["schemas"]["artworkspec_Annotated_String"] | null;
      binding?: components["schemas"]["artworkspec_Annotated_String"] | null;
      placementInMagazine?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      maxFileSize?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmount"]
        | null;
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    artworkspec_PrintOOH: {
      artworkDimension?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensionOptions"]
        | null;
      artworkBleed?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintBorderDimensions"]
        | null;
      artworkScale?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      visualSafeArea?:
        | components["schemas"]["artworkspec_Annotated_common_Unit"]
        | null;
      physicalDimension?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensionOptions"]
        | null;
      physicalBleed?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintBorderDimensions"]
        | null;
      finishedEdgedDimensions?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      edging?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintBorderDimensions"]
        | null;
      illumination?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_Illumination"]
        | null;
      install?: components["schemas"]["artworkspec_Annotated_String"] | null;
      formats?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintMediaFormat"]
        | null;
      maxFileSize?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_DataAmount"]
        | null;
      resolution?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintResolution"]
        | null;
      font?: components["schemas"]["artworkspec_Annotated_String"] | null;
      colourProfile?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      blackSpecification?:
        | components["schemas"]["artworkspec_Annotated_String"]
        | null;
      materialAttributes?:
        | components["schemas"]["artworkspec_Attributes"]
        | null;
      attributes?: components["schemas"]["artworkspec_Attributes"];
    };
    artworkspec_PrintDimensionOptions: {
      visualSize?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions"]
        | null;
      finishSize?:
        | components["schemas"]["artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensions"]
        | null;
    };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_PrintDimensionOptions: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_PrintDimensionOptions"];
    };
    artworkspec_Illumination:
      | {
          backlit: components["schemas"]["artworkspec_Backlit"];
        }
      | {
          frontlit: components["schemas"]["artworkspec_Frontlit"];
        };
    artworkspec_Backlit: { [key: string]: unknown };
    artworkspec_Frontlit: { [key: string]: unknown };
    /** A value - optionally with metadata */
    artworkspec_Annotated_kachemedia_specsheet_artworkspec_Illumination: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      value: components["schemas"]["artworkspec_Illumination"];
    };
    /** A value with an optional name and metadata */
    artworkspec_NamedAnnotated_kachemedia_specsheet_artworkspec_ArtworkSpec: {
      metadata?: components["schemas"]["artworkspec_Metadata"] | null;
      name?: string | null;
      value: components["schemas"]["artworkspec_ArtworkSpec"];
    };
    Instant: number;
    LocalDate: string;
    db_Version: number;
    /** A Campaign / Contract. */
    ApiCampaign: {
      campaignIdentifier: components["schemas"]["ApiCampaignId"];
      client: string;
      campaignName?: string;
    };
    ApiCampaignId: string;
    /** A placement booked at a date in a campaign */
    ApiBooking: {
      bookingIdentifier: components["schemas"]["ApiBookingId"];
      placementIdentifier: components["schemas"]["ApiPlacementId"];
      campaignIdentifier: components["schemas"]["ApiCampaignId"];
      liveDate: components["schemas"]["LocalDate"];
      endDate: components["schemas"]["LocalDate"];
    };
    ApiBookingId: string;
    /** Basic success or unspecified error response. */
    SuccessOrError:
      | "success"
      | {
          error: components["schemas"]["Unit"];
        };
    /** Request batch update/create of placements, campaigns and bookings */
    BatchDeleteReq: {
      reqId?: string;
      placements?: components["schemas"]["ApiPlacementId"][];
      campaigns?: components["schemas"]["ApiCampaignId"][];
      bookings?: components["schemas"]["ApiBookingId"][];
    };
  };
}

export interface operations {
  /** Batch update of placement, booking and campaign data */
  batchUpdate: {
    parameters: {};
    responses: {
      /** success */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessOrError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchUpdateReq"];
      };
    };
  };
  /** Batch delete of placements, booking or campaign */
  batchDelete: {
    parameters: {};
    responses: {
      /** success */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessOrError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchDeleteReq"];
      };
    };
  };
}

export interface external {}
